Refactor install and dependencies trigger

diff --git a/dependencies b/dependencies
--- a/dependencies
+++ b/dependencies
@@ -4,10 +4,32 @@
 
 set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
 
-export DEBIAN_FRONTEND=noninteractive
 
-case "$DOKKU_DISTRO" in
-  debian|ubuntu)
-    apt-get install --force-yes -qq -y monit
-    ;;
-esac
+install_monit() {
+    case "$DOKKU_DISTRO" in
+        debian|ubuntu)
+            export DEBIAN_FRONTEND=noninteractive
+            apt-get install --force-yes -qq -y monit
+            ;;
+        *)
+            echo "Unsupported distribution. Please install Monit and run sudo dokku plugin:install-dependencies again."
+            return 1
+    esac
+}
+
+enable_systemd_unit() {
+    local plugin_path="$PLUGIN_AVAILABLE_PATH/monit"
+
+    if hash systemctl 2> /dev/null; then
+        systemctl is-enabled dokku-monit.service > /dev/null 2>&1 || systemctl enable "$plugin_path/dokku-monit.service" --now
+    else
+        echo >&2 "Could not install systemd unit because systemctl was not found."
+        return 1
+    fi
+}
+
+if hash monit 2> /dev/null; then
+    enable_systemd_unit
+else
+    install_monit && enable_systemd_unit
+fi
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,17 @@
 #!/usr/bin/env bash
 set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
 
+enable_systemd_unit() {
+    local plugin_path="$PLUGIN_AVAILABLE_PATH/monit"
+
+    if hash systemctl 2> /dev/null; then
+        systemctl is-enabled dokku-monit.service > /dev/null 2>&1 || systemctl enable "$plugin_path/dokku-monit.service" --now
+    else
+        echo >&2 "Could not install systemd unit because systemctl was not found."
+        return 1
+    fi
+}
+
 plugin-install() {
     local plugin_path="$PLUGIN_AVAILABLE_PATH/monit"
 
@@ -11,7 +22,11 @@ plugin-install() {
         chmod 0500 "$DOKKU_ROOT/.monitrc"
     fi
 
-    systemctl enable "$plugin_path/dokku-monit.service" --now
+    if hash monit 2> /dev/null; then
+        enable_systemd_unit
+    else
+        echo >&2 "Could not find Monit. Please run dokku plugin:install-dependencies."
+    fi
 }
 
 plugin-install
